ci: run only basic import tkinter check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,7 @@ on:
     branches:
       - 'develop'
       - 'v4'
+      - 'debug-macos-py3101'
   pull_request:
     branches:
       - '**'
@@ -18,116 +19,17 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        python-version: [3.7, 3.8, 3.9, '3.10']
-        os: ['windows-latest', 'ubuntu-latest', 'macos-10.15', 'macos-latest']
+        python-version: ['3.10.0', '3.10.1', '3.10.2']
+        os: ['macos-10.15', 'macos-11']
       fail-fast: false
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
+      - uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Install apt packages
-        if: startsWith(matrix.os, 'ubuntu')
+      - name: Check for presence of Tcl/Tk 8.6 libraries
         run: |
-          sudo apt-get update -qq
-          sudo apt-get install -qq --no-install-recommends \
-            libxml2-dev libxslt1-dev gfortran libatlas-base-dev \
-            libespeak1 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 \
-            libxkbcommon-x11-0 libxcb-icccm4 libxcb1 openssl \
-            libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev \
-            libxcb-shape0-dev libxcb-xkb-dev xvfb \
-            libopengl0 libegl1 \
-            libpulse0 libpulse-mainloop-glib0 \
-            libgstreamer-plugins-base1.0-0 libgstreamer-gl1.0-0 \
-            gir1.2-gtk-3.0 libgirepository1.0-dev
+          ls -l /usr/local/lib/libtcl* || echo "Tcl/Tk 8.6 not found!"
 
-      - name: Download AppImage tool
-        if: startsWith(matrix.os, 'ubuntu')
-        run: |
-          wget \
-            https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage \
-            -O $HOME/appimagetool-x86_64.AppImage
-          chmod a+x $HOME/appimagetool-x86_64.AppImage
-
-      - name: Set cache dir
-        run: echo "pip_cache_dir=$(pip cache dir)" >> $GITHUB_ENV
-        shell: bash
-
-      - name: Fetch cache
-        id: cache-target
-        uses: actions/cache@v2
-        with:
-          path: ${{ env.pip_cache_dir }}
-          key: ${{ runner.os }}-${{ matrix.python-version }}
-
-      - name: Check if bootloader code conforms to gnu90 C standard
-        if: startsWith(matrix.os, 'ubuntu')
-        run: |
-          # Compile bootloader
-          cd bootloader
-          CC="gcc -std=gnu90" python waf all
-          cd ..
-
-      - name: Set up environment
-        run: |
-          # Update pip.
-          python -m pip install -U pip setuptools wheel
-
-          # Install dependencies for tests.
-          pip install --progress-bar=off -U -r tests/requirements-tools.txt -r tests/requirements-libraries.txt
-          # Compile bootloader
-          cd bootloader
-          python waf all
-          cd ..
-
-          # Install PyInstaller.
-          pip install --progress-bar=off .
-
-          # Make sure the help options print.
-          python -m pyinstaller -h
-
-          # Run Qt-based tests with offscreen backend
-          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV
-
-      - name: Start display server
-        if: startsWith(matrix.os, 'ubuntu')
-        run: |
-          Xvfb :99 &
-          echo "DISPLAY=:99" >> $GITHUB_ENV
-
-      # Required on macOS 11 by tests that register custom URL schema. This could also be achieved by passing
-      # --basetemp to pytest, but using environment variable allows us to have a unified "Run test" step for
-      # all OSes.
-      - name: Relocate temporary dir
-        if: matrix.os == 'macos-11' || matrix.os == 'macos-latest'
-        run: |
-          echo "PYTEST_DEBUG_TEMPROOT=$RUNNER_TEMP" >> $GITHUB_ENV
-
-      - name: Run tests
-        uses: xoviat/actions-pytest@0.1-alpha2
-        with:
-          args: >
-            -n 3 --maxfail 3 --durations 10 tests/unit tests/functional
-            --force-flaky --no-flaky-report --reruns 3 --reruns-delay 10
-
-      - name: Run hooksample tests
-        run: |
-          # The ``run_tests`` script is invoked with the ``-c`` option to
-          # specify a ``pytest.ini``, rather than allowing pytest to find
-          # something unexpected in the filesystem (it searches from the root
-          # dir all the way to the top of the filesystem per
-          # https://docs.pytest.org/en/latest/customize.html).
-          python -m PyInstaller.utils.run_tests -c PyInstaller/utils/pytest.ini --include_only=pyi_hooksample.
-
-  test-alpine:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - run: docker build -f alpine.dockerfile -t foo .
-      - run: >
-          docker run foo pytest
-          -n 3 --maxfail 3 --durations 10 tests/unit tests/functional
-          --force-flaky --no-flaky-report --reruns 3 --reruns-delay 10
+      - name: Try importing tkinter
+        run: python3 -c 'import tkinter'
